### ISSUE TITLE
$model->setAttributes() does not populate all properties

### ISSUE THREAD

**Issue by set-killer** [yiisoft/yii2-mongodb#331]
### What steps will reproduce the problem?
I have the following model declaration:

```php
namespace app\modelsMongo;

use yii\mongodb\ActiveRecord;

class Test extends ActiveRecord {
    public static function collectionName() {
        return 'test-deleteme';
    }

    public function rules() {
        return [
            [['uuid'], 'required'],
        ];
    }

    public function attributes() {
        return [
            '_id',
            'uuid',
            'name', 
        ];
    }
}
```
After that i try to populate the model as follows:

```php
$model = new Test();
$model->setAttributes([
    "uuid" => "aaa-bbb-ccc",
    "name" => "my name"
]);
$model->save();
```

As a result only the `uuid` property is filled into the database and the `name` property is missing.
This is what's saved in the database:

```json
  {
    "_id": {
      "$oid": "60211511bf439768de191e02"
    },
    "uuid": "aaa-bbb-ccc"
  }
```

### Additional info

| Q                      | A
| ---------------------- | ---
| Yii version            | 2.0.40
| Yii MongoDB version    | 2.1.11
| MongoDB server version | 4.0.11
| PHP version            | 7.2
| Operating system       | Linux

**Comment by samdark** [comment]
That is expected behavior. By default, only safe fields could be mass-assigned. Safe field is a field that either has a validation rule or explicitly marked with `safe` rule. In your case you don't have any validation rule for `name` thus it is considered unsafe to mass-assign it. If you're absolutely sure you can't have a validation rule for it you can do `setAttributes($values, false)`.

**Comment by set-killer** [comment]
Okay, thank you.
